// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type BlockIndexedInterval struct {
	IdxFromBlockHeight int `json:"idxFromBlockHeight" firestore:"idxFromBlockHeight"`
	IdxToBlockHeight   int `json:"idxToBlockHeight" firestore:"idxToBlockHeight"`
}

type ChainInfo struct {
	LastBlockHeightReceived int                 `json:"lastBlockHeightReceived" firestore:"lastBlockHeightReceived"`
	ChainID                 string              `json:"chainID" firestore:"chainID"`
	CosmosMsgs              []*CosmosMsgIndexed `json:"cosmosMsgs" firestore:"cosmosMsgs"`
}

type CosmosMsgIndexed struct {
	ProtoMsgName           string                  `json:"protoMsgName" firestore:"msgType"`
	BlocksIndexed          []*BlockIndexedInterval `json:"blocksIndexed" firestore:"blocksIndexed"`
	IdxHeighestBlockHeight int                     `json:"idxHeighestBlockHeight" firestore:"idxHeighestBlockHeight"`
}

type Query struct {
}
