package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"
	"fmt"

	"github.com/umee-network/umeed-indexer/graph/types"
)

// GetLiquidateMsgs is the resolver for the getLiquidateMsgs field.
func (r *queryResolver) GetLiquidateMsgs(ctx context.Context, borrower string) ([]*types.IndexedTx, error) {
	panic(fmt.Errorf("not implemented: GetLiquidateMsgs - getLiquidateMsgs"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
